### ISSUE TITLE
Set up GSuite schedule and get others to do the same so everyone can schedule meetings

### ISSUE THREAD

**Issue by lehighjcut** [dolomite-exchange/dolomite#10]
- [x] Overall Dolomite Calendar (work together on this but mostly Jordan)
- [x] Jordan's Calendar
- [x] Corey's Calendar
- [x] Adam's Calendar

Once all of us have our calendars done on our new /@dolomite.com accounts we can have people schedule meeting times with us

**Comment by lehighjcut** [comment]
@coreycaplan3 @aknuck close issue when you send the invites out to everyone

**Comment by coreycaplan3** [comment]
Finished mine. @aknuck you're up.

**Comment by coreycaplan3** [comment]
I did Adam's for him.
