### ISSUE TITLE
Set up example of dependency injection using HOCs (IF YOU THINK ITS A GOOD IDEA)

### ISSUE THREAD

**Issue by lehighjcut** [dolomite-exchange/dolomite#2]
(see this link for how to: https://medium.com/front-end-hacking/reactjs-hoc-how-to-inject-dependencies-to-react-component-in-angularjs-way-a2fc63d795c8)

**Comment by zrubenst** [comment]
It is a good idea! Created a few HOCs for the Dolomite Theme
