### ISSUE TITLE
Material ui customization - Example

### ISSUE THREAD

**Issue by lehighjcut** [dolomite-exchange/dolomite#3]
Example of using buttons and some other Material UI component that has been customized with the theme and customized on top of that with scss classes on top of it.

Probably can do one where we make our own Wrapped DolomiteButton for example with its own scss, which can just be imported and used everywhere, and then one where its more like a one-off scss change in that particular component which the themed ui component is being used

**Comment by zrubenst** [comment]
Finished with this PR: https://github.com/dolomite-exchange/dolomite/pull/17
