### ISSUE TITLE
Let Zack Know How Auth / Request Headers will look so he can set up interceptors

### ISSUE THREAD

**Issue by lehighjcut** [dolomite-exchange/dolomite#34]
Zack can set up http interceptors on the front-end (I already have the boilerplate for it) to automatically append info like headers to every request. Will this be relevant or can we delete the boilerplate for it?

**Comment by coreycaplan3** [comment]
There will be a simple API key to be added to the header. Just add that code to be able to add an arbitrary key and we'll be good.
